### ISSUE TITLE
Adding easier setup for quicker prototyping. 

### ISSUE THREAD

**Issue by seivan** [Lokathor/fermium#15]
I like this approach more as it doesn't require you to keep a bunch of tabs on two documentation pages (RustSDL and SDL) 
However, it's missing some stuff that would make it useful for production.

1) iOS and Android
2) The ability to work without user having SDL pre-installed and in path.

I understand that the second option isn't that much useful for production given that Steam won't let you run your own SDL(?) but it's useful for development purposes and general testing. 

Since there is support for static linking, is there a chance that this crate could also pull down SDL2 or use the platforms ability to handle this ?
E.g on macOS (for both arm and x64)  it would check with Homebrew first for the correct version, if not, download SDL2 and build it in current directory (not in lib paths) and use it from there?

**Comment by Lokathor** [comment]
* iOS and Android support I plan to get to at some point, I just currently lack the expertise.

* For a self-setup step, I guess I could arrange for that to be placed as a curl script for linux and one for mac, but I don't really wanna make it a feature in the build script itself.

**Comment by seivan** [comment]
I can take a stab at iOS - if I decide to use fermium. 

I think it should be part of the build script if opt-in. 
I'd love to opt-in for dev, the ability to just use this crate and get SDL up and running beats having to do all that work. 


If you're OK with it, I could add support for at least macOS/iOS targets. 
I'd use homebrew and it it fails, go the manual route - but what I want to make sure is that we don't mess with the users folders, and isolate it within a directory as part of the target folder.

**Comment by Lokathor** [comment]
i mean, "all that work" is a one time install. that's not per project/crate, that's per operating system install.

i don't want to have a feature that causes the crate to install to a global location, but a feature to auto-install to the out directory and have that all automatically work would probably be okay.

be warned, i do _not_ think that such a feature woyld actually give a very good "quick setup" experience. building sdl2 from source is like 2 minutes to do.

**Comment by seivan** [comment]
@Lokathor For every person I send a project to that's a whole ordeal to go through... after I've convinced them to get started with rustup and add stuff to their `.zshrc/.profile` I just want to emulate Xcodes `cmd+r` for running a project - that's all :) 

But I understand your stance and I agree with it. 
My stance is, if homebrew is in a users path, then using homebrew is probably a better approach - otherwise as a fall back pulling down sdl2.tars to the out director and get started on that works - with the former being much faster than two minutes ;-)

**Comment by Lokathor** [comment]
Let's break this up into two issues, because the skill sets involved aren't necessarily the same:
* https://github.com/Lokathor/fermium/issues/25
* https://github.com/Lokathor/fermium/issues/24

I think we can close this for now, though I'll continue to work on making setup as easy as is practical.
