### ISSUE TITLE
SDL_GetWindowWMInfo is missing from macOS 

### ISSUE THREAD

**Issue by seivan** [Lokathor/fermium#16]
`SDL_GetWindowWMInfo()`

Doesn't seem to exist for the generated binding for macOS.

**Comment by Lokathor** [comment]
Hmm.

The function seems to be in the includes we're using: https://github.com/Lokathor/fermium/blob/master/include/SDL_syswm.h#L312

Not sure why bindgen isn't picking this one up.

Feel free to investigate but note that it's missing from all operating systems not just MacOS, so maybe that include file isn't getting pulled in by other include files correctly or something like that?

**Comment by seivan** [comment]
Maybe bindgen only picks it up if you include `syswm.h`? I'm pretty sure its platform dependent code to.

**Comment by Lokathor** [comment]
at the moment everything gets pulled in automatically by having just `SDL.h` without any other imports, but it's totally possible that a second import is supposed to be on the list if you want extra platform code.

have you used the wm info with SDL2 in C? do you know what the expectations are there?

**Comment by seivan** [comment]
@Lokathor Not exactly.

But I suspect adding it to `wrapper.h`

```
#include "SDL_syswm.h"
```

**Comment by Lokathor** [comment]
well no one should be unconditionally using bindgen. anyone who is needs to get with the program and make it optional.

that said, i have a setting to just invoke the bindgen cli, which will not put a bindgen dependency in the build chain, so you could use that.

I'm wary of adding too many includes that might reduce the default level of portability, but if mac folks need those extra headers to get by then we can probably get that added in as a MacOS conditional part of the main header.

**Comment by seivan** [comment]
I need those for Windows to :P they're not platform dependent per say, but do contain variations between platforms for the struct. So this one in particular should be default be included regardless of platform and let SDL deal with the variations.

**Comment by Lokathor** [comment]
I admit that I found myself wondering earlier how you'd be able to tell if your program was a window or was enforced to be fullscreen. :ferristhonk:

Alright I'll try to get this adjusted tonight, though I'll need you or someone else to rebuild the mac file.

**Comment by seivan** [comment]
@Lokathor Ready whenever you are. I like your approach a lot more than the current bindings and wrappers as more often than not, things don't work. 
Perhaps it was mistake to wrap SDL so much as the interface against SDL is mostly for window creation, playing sounds and events - the surface area is small but it's vital *THINGS WORK* when they need to.

**Comment by Lokathor** [comment]
Closing this in favor of a more clearly stated https://github.com/Lokathor/fermium/issues/20, where I can remember what I'm supposed to do better.
