### ISSUE TITLE
SDL_Keysym fields are private

### ISSUE THREAD

**Issue by wbogocki** [Lokathor/fermium#73]
`SDL_Keysym` is the type of the `SDL_KeyboardEvent`'s `keysym` field.

It's relevant because:

```rust
match event.type_ {
    SDL_KEYDOWN => {
        if event.key.keysym.sym == SDLK_ESCAPE { // Error, event.key.keysym.sym is private
            done = true;
        }
    },
    _ => (),
}
```

This is very basic usage so I'm probably just blind and not seeing some obvious right way to do this... however, I searched through the docs and the internet and couldn't figure it out.

Is this an actual omission?

**Comment by Lokathor** [comment]
Entirely my fault. I copied some code forward from a previous version that had declared structs via macro, so i had to apply the `pub` by hand and didn't do so in some cases. I'll try to get a fix out right away.

**Comment by wbogocki** [comment]
Awesome, man. Thanks!

**Comment by Lokathor** [comment]
published
