### ISSUE TITLE
SDLK_ESCAPE has incorrect value

### ISSUE THREAD

**Issue by wbogocki** [Lokathor/fermium#74]
Feels funny reporting one issue after another.

```rust
match event.type_ {
    SDL_KEYDOWN => {
        // The value of `event.key.keysym.sym` is 27 when escape is hit. The value in `SDLK_Escape` is 33.
        if event.key.keysym.sym == SDLK_ESCAPE {
            done = true;
        }
    },
    _ => (),
}
```

Looks like this has a history back to [2014](https://github.com/torch/sdl2-ffi/issues/1) :) Possibly SDL changed the keycode at some point.

**Comment by wbogocki** [comment]
Some more context: https://wiki.libsdl.org/SDLKeycodeLookup

Looks like this could be where the error came from.

**Comment by Lokathor** [comment]
The header file says

`SDLK_ESCAPE = '\033',`

which... I guess is like octal 33 maybe? or something? I'll have to fix it when i get home to a proper computer for testing. Or, if you figure it out I'll accept a PR.

**Comment by wbogocki** [comment]
Yes, it's octal. I'll submit a PR.

**Comment by Lokathor** [comment]
who on earth is writing octal values in their header files in the year of ferris 2021 :(

**Comment by wbogocki** [comment]
SDL 2 creators apparently :^)

I had to do a force push to undo my auto-formatter. It's showing two commits here. It should just be one with only `SDLK_ESCAPE` value changed. Please review and if looks good 🎉

**Comment by Lokathor** [comment]
okay, patch released for this.

**Comment by wbogocki** [comment]
Thanks! You're awesome!
