### ISSUE TITLE
The `SDL_PIXELFORMAT_RGBA32` constant is set to the wrong value.

### ISSUE THREAD

**Issue by NightShade256** [Lokathor/fermium#77]
The `SDL_PIXELFORMAT_RGBA32` alias is set the `SDL_PIXELFORMAT_RGBA8888` on big endian systems while it is set to `SDL_PIXELFORMAT_ABGR8888` on little endian systems. [SDL Wiki](https://wiki.libsdl.org/SDL_PixelFormatEnum).

In the bindings however it is the other way around.

![image](https://user-images.githubusercontent.com/25431369/113137311-05ef5580-9242-11eb-96f8-59b853dc8511.png)

**Comment by Lokathor** [comment]
Fixed in `fermium-20014.4.2`
