### ISSUE TITLE
Build failing on Ubuntu 22

### ISSUE THREAD

**Issue by Wormss9** [Lokathor/fermium#86]
Hi, when I try to build a project with fermium i get an `error: failed to run custom build command for 'fermium v20016.1.1'`.
I get `undefined reference to 'wl_proxy_marshal_flags'` error during build witch should be fixed in SDL, https://github.com/libsdl-org/SDL/pull/5092

**Comment by Lokathor** [comment]
Ah, the version of SDL2 in this crate is older than that patch.

Unfortunately I haven't had time for this crate in a long while. It's still back on SDL2-2.0.16. If you want to PR the fix yourself all you'd have to do is update the crate to newer SDL by replacing the folders and adjust the build.rs to use the new folder names. If not, I'm not sure if i can get to this right away but I'll try to.

of course, the sdl2 and sdl2-sys crates might work instead on the meantime.

did this crate get used in a tutorial that got linked somewhere or something? you're the second new person to file an issue out of the blue this month after a long time of inactivity.

**Comment by Wormss9** [comment]
https://rust-tutorials.github.io/learn-opengl/introduction.html

**Comment by Lokathor** [comment]
yeah but i didn't think anyone was actually *reading* my tutorial XD
