### ISSUE TITLE
unstable library feature `core_ffi_c`

### ISSUE THREAD

**Issue by Des-Nerger** [Lokathor/fermium#92]
It seems `core_ffi_c` has been stabilized only since Rust 1.64. I had 1.63, hence couldn't compile the last fermium from crates.io. I guess it'd be better to add `rust-version = "1.64"` in fermium's `Cargo.toml` 🤔.

**Comment by Lokathor** [comment]
Updated in https://github.com/Lokathor/fermium/commit/5aed0ca7ed0f96ad9f83aa5bf29174b921c1dd65
