### ISSUE TITLE
sdl.create_surface_from takes in a static-sized array instead of a Vec

### ISSUE THREAD

**Issue by andylovescode** [Lokathor/fermium#95]
I want to dynamically create a texture of a dynamic size, but rust's arrays have to be a known size at compile time, so I would appreciate it if there is a change to the existing api, or a new api that takes in a Vec instead of an array.

## Requested API

```rust
pub fn create_surface_from_vec(
    &self, pixels: Vec<r8g8b8a8_Srgb>, width: i32, height: i32,
)
```

**Comment by Lokathor** [comment]
https://github.com/Lokathor/beryllium/blob/main/src/surface.rs#L24

are you referring to this method in the beryllium crate?

That method takes a slice, so a reference to a vec would work because rust would convert it into a slice at the call site.

**Comment by andylovescode** [comment]
Yes, you're correct, thanks!
